spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/javaweb
      username: root
      password: Ss123456789
server:
  port: 8081
